#ifndef SRC_UI_ICONS
#define SRC_UI_ICONS

// Icon indirection: screens name a *slot*, never a glyph.
//
// Each theme maps the same slots to its own glyphs, so switching theme is one
// font swap and screen code never changes. Slots live in the Unicode Private
// Use Area at a fixed, stable numbering -- an icon set is chosen at build/run
// time, the codepoints are not.
//
// Themes:
//   builtin  - LVGL's bundled symbols (a FontAwesome subset). Free, always
//              available, drawn by the normal text font. The fallback.
//   material - Material Symbols (Apache-2.0), generated by
//              tools/make-icon-font.sh into src/ui/icons_material.c.
//
// Icons are monochrome: they take the label's text colour, which is what
// makes theming and night mode free. Brand marks (Android Auto / CarPlay
// logos) are deliberately *not* here -- they need colour bitmaps and carry
// trademark terms of their own.

#ifdef USE_LVGL

#include <lvgl/lvgl.h>

namespace icons
{
enum Id
{
    ICON_USB = 0,
    ICON_WIRELESS,
    ICON_DONGLE,
    ICON_SETTINGS,
    ICON_BACK,
    ICON_NIGHT,
    ICON_VIDEO,
    ICON_DEBUG,
    ICON_THEME,
    ICON_RESTART,
    ICON_COUNT,
};

// Selects the theme from Settings::iconTheme, falling back to "builtin" if the
// requested set was not built in. Call once before creating screens.
void begin();

// UTF-8 text for this slot in the active theme.
const char *text(Id id);

// Font that can draw the active theme's icons at this panel height. For the
// builtin theme this is just the body font; a generated icon set has its own.
const lv_font_t *font(int height);

// True when a dedicated icon font is in use (icons then need their own label,
// since one label can only have one font).
bool separateFont();
} // namespace icons

#endif /* USE_LVGL */
#endif /* SRC_UI_ICONS */
