#ifndef SRC_UI_ICONS_MATERIAL
#define SRC_UI_ICONS_MATERIAL

// GENERATED by tools/make-icon-font.sh -- do not edit.
// Material Symbols (Apache-2.0), subset to the slots in icons.h.

#include <lvgl/lvgl.h>

#ifdef __cplusplus
extern "C"
{
#endif
    extern const lv_font_t icons_material_14;
    extern const lv_font_t icons_material_20;
    extern const lv_font_t icons_material_28;
#ifdef __cplusplus
}
#endif

// Icon tier, mirroring the body-font tiers in screen_picker.cpp.
static inline const lv_font_t *icons_material_font(int height)
{
    if (height <= 272)
        return &icons_material_14;
    if (height <= 480)
        return &icons_material_20;
    return &icons_material_28;
}

#endif /* SRC_UI_ICONS_MATERIAL */
