#include "icons.h"

#ifdef USE_LVGL

#include "common/logger.h"
#include "settings.h"

// Generated by tools/make-icon-font.sh; absent until that has been run, which
// is why the theme falls back to the bundled symbols rather than failing.
#if __has_include("icons_material.h")
#include "icons_material.h"
#define ICONS_HAVE_MATERIAL 1
#endif

namespace
{
bool g_material = false;

// Slot -> glyph for the builtin theme. LVGL bundles a FontAwesome subset in
// the Montserrat fonts, so these cost nothing extra. Coverage is coarse (no
// distinct "dongle"), which is exactly why the Material theme exists.
const char *const BUILTIN[icons::ICON_COUNT] = {
    LV_SYMBOL_USB,       // ICON_USB
    LV_SYMBOL_WIFI,      // ICON_WIRELESS
    LV_SYMBOL_SD_CARD,   // ICON_DONGLE  (nearest available)
    LV_SYMBOL_SETTINGS,  // ICON_SETTINGS
    LV_SYMBOL_LEFT,      // ICON_BACK
    LV_SYMBOL_EYE_CLOSE, // ICON_NIGHT   (nearest available)
    LV_SYMBOL_VIDEO,     // ICON_VIDEO
    LV_SYMBOL_WARNING,   // ICON_DEBUG   (nearest available)
    LV_SYMBOL_IMAGE,     // ICON_THEME   (nearest available)
    LV_SYMBOL_REFRESH,   // ICON_RESTART
};

#ifdef ICONS_HAVE_MATERIAL
// Same order as icons::Id. Codepoints are assigned by
// tools/make-icon-font.sh, which remaps each Material glyph onto these -- so
// the numbering below and the script's ICON_SLOTS list must stay in step.
const char *const MATERIAL[icons::ICON_COUNT] = {
    "\xEF\x80\x81", // U+F001 ICON_USB
    "\xEF\x80\x82", // U+F002 ICON_WIRELESS
    "\xEF\x80\x83", // U+F003 ICON_DONGLE
    "\xEF\x80\x84", // U+F004 ICON_SETTINGS
    "\xEF\x80\x85", // U+F005 ICON_BACK
    "\xEF\x80\x86", // U+F006 ICON_NIGHT
    "\xEF\x80\x87", // U+F007 ICON_VIDEO
    "\xEF\x80\x88", // U+F008 ICON_DEBUG
    "\xEF\x80\x89", // U+F009 ICON_THEME
    "\xEF\x80\x8A", // U+F00A ICON_RESTART
};
#endif
} // namespace

namespace icons
{
void begin()
{
    const bool wantMaterial = Settings::iconTheme.value == "material";

#ifdef ICONS_HAVE_MATERIAL
    g_material = wantMaterial;
#else
    g_material = false;
    if (wantMaterial)
        log_w("Icon theme 'material' not built (run tools/make-icon-font.sh) > using builtin");
#endif

    log_v("Icon theme: %s", g_material ? "material" : "builtin");
}

const char *text(Id id)
{
    if (id < 0 || id >= ICON_COUNT)
        return "";

#ifdef ICONS_HAVE_MATERIAL
    if (g_material)
        return MATERIAL[id];
#endif
    return BUILTIN[id];
}

const lv_font_t *font(int height)
{
#ifdef ICONS_HAVE_MATERIAL
    if (g_material)
        return icons_material_font(height);
#endif
    // Builtin symbols live in the Montserrat fonts, so mirror the body tier.
    if (height <= 272)
        return &lv_font_montserrat_14;
    if (height <= 480)
        return &lv_font_montserrat_20;
    return &lv_font_montserrat_28;
}

bool separateFont()
{
    return g_material;
}
} // namespace icons

#endif /* USE_LVGL */
