#ifndef SRC_UI_LVGL_OSD
#define SRC_UI_LVGL_OSD

// LVGL bound to an SDL_Renderer, so one backend serves both render paths:
//   - renderer = sdl  (desktop / Pi dev): the window's renderer,
//   - renderer = drm  (F1C200s): drm_display::uiRenderer(), a *software*
//     renderer targeting the offscreen ARGB surface that is flipped onto the
//     DRM overlay plane above the hardware video.
// LVGL renders into a small partial buffer; each flush lands in a streaming
// ARGB texture, which render() copies to the renderer. The caller owns
// presentation (SDL_RenderPresent / drm_display::uiPresent()).
//
// The UI itself (screens, styles, flow) is generated by EEZ Studio into
// src/ui/generated -- never hand-edited, always regenerated from ui.eez-project.

#ifdef USE_LVGL

#include <SDL2/SDL.h>

class LvglOsd
{
public:
    LvglOsd() = default;
    ~LvglOsd();

    // Creates the LVGL display/input at the given size and builds the
    // generated screens. Size comes from the caller (the DRM panel, or the SDL
    // window), never a compile-time constant.
    bool begin(SDL_Renderer *renderer, int width, int height);
    void end();
    bool active() const { return _disp != nullptr; }

    // Feed pointer state (SDL mouse/touch on the desktop path, evdev/GT911 on
    // the device path). Coordinates are in display pixels.
    void pointer(int x, int y, bool pressed);

    // Feed a 3-way rotary encoder: `steps` is the rotation since the last
    // call (negative = left), `pressed` is the push button. Head units often
    // have only this, so every screen must be fully operable through it.
    void encoder(int steps, bool pressed);

    // Runs the flow + LVGL timers and copies the result to the renderer.
    void render();

    // Split form for callers that pace themselves: tick() runs the flow +
    // LVGL timers and reports whether LVGL flushed anything to the texture
    // since the last blit(); blit() copies the texture to the renderer. When
    // tick() returns false the screen is unchanged and the caller can skip
    // the clear/copy/present entirely (on the F1C200s a full 800x480 software
    // present costs more than a 60 fps frame budget, so presenting every
    // iteration pinned the core while the UI sat idle).
    bool tick();
    void blit();

    // Like blit(), but copies only the union of the rectangles LVGL flushed
    // since the last blit and returns it (empty rect if nothing changed). The
    // renderer's target keeps its contents between frames, so partial blits
    // are enough once a full blit has happened.
    SDL_Rect blitDirty();

private:
    // LVGL types are kept out of this header so including it (e.g. from
    // application.cpp) does not drag in lvgl.h; the .cpp casts them back.
    friend struct LvglOsdCallbacks;

    SDL_Renderer *_renderer = nullptr;
    SDL_Texture *_texture = nullptr;
    void *_disp = nullptr;
    void *_indev = nullptr;
    void *_encoder = nullptr;
    uint8_t *_buffer = nullptr;
    int _encSteps = 0;
    bool _encPressed = false;
    int _width = 0;
    int _height = 0;
    int _px = 0, _py = 0;
    bool _flushed = true; // texture changed since the last blit()
    SDL_Rect _dirty{0, 0, 0, 0}; // union of flushed areas since the last blit()
    bool _pressed = false;
    bool _generated = false; // EEZ screens vs the built-in picker
};

#endif /* USE_LVGL */
#endif /* SRC_UI_LVGL_OSD */
