#ifndef SRC_UI_LVGL_OSD
#define SRC_UI_LVGL_OSD

// LVGL bound to an SDL_Renderer, so one backend serves both render paths:
//   - renderer = sdl  (desktop / Pi dev): the window's renderer,
//   - renderer = drm  (F1C200s): drm_display::uiRenderer(), a *software*
//     renderer targeting the offscreen ARGB surface that is flipped onto the
//     DRM overlay plane above the hardware video.
// LVGL renders into a small partial buffer; each flush lands in a streaming
// ARGB texture, which render() copies to the renderer. The caller owns
// presentation (SDL_RenderPresent / drm_display::uiPresent()).
//
// The UI itself (screens, styles, flow) is generated by EEZ Studio into
// src/ui/generated -- never hand-edited, always regenerated from ui.eez-project.

#ifdef USE_LVGL

#include <SDL2/SDL.h>

class LvglOsd
{
public:
    LvglOsd() = default;
    ~LvglOsd();

    // Creates the LVGL display/input at the given size and builds the
    // generated screens. Size comes from the caller (the DRM panel, or the SDL
    // window), never a compile-time constant.
    bool begin(SDL_Renderer *renderer, int width, int height);
    void end();
    bool active() const { return _disp != nullptr; }

    // Feed pointer state (SDL mouse/touch on the desktop path, evdev/GT911 on
    // the device path). Coordinates are in display pixels.
    void pointer(int x, int y, bool pressed);

    // Feed a 3-way rotary encoder: `steps` is the rotation since the last
    // call (negative = left), `pressed` is the push button. Head units often
    // have only this, so every screen must be fully operable through it.
    void encoder(int steps, bool pressed);

    // Runs the flow + LVGL timers and copies the result to the renderer.
    void render();

private:
    // LVGL types are kept out of this header so including it (e.g. from
    // application.cpp) does not drag in lvgl.h; the .cpp casts them back.
    friend struct LvglOsdCallbacks;

    SDL_Renderer *_renderer = nullptr;
    SDL_Texture *_texture = nullptr;
    void *_disp = nullptr;
    void *_indev = nullptr;
    void *_encoder = nullptr;
    uint8_t *_buffer = nullptr;
    int _encSteps = 0;
    bool _encPressed = false;
    int _width = 0;
    int _height = 0;
    int _px = 0, _py = 0;
    bool _pressed = false;
    bool _generated = false; // EEZ screens vs the built-in picker
};

#endif /* USE_LVGL */
#endif /* SRC_UI_LVGL_OSD */
