#!/bin/sh
# Build the "material" icon theme: a Material Symbols (Apache-2.0) subset,
# converted to LVGL fonts at the three panel tiers.
#
# Only the handful of glyphs the UI actually names are included, so the whole
# theme costs ~10-20 KB rather than shipping a 3,700-icon font.
#
# Each glyph is remapped onto the fixed Private Use Area slot that
# src/ui/icons.h declares. That indirection is the point: another icon set can
# be built to the *same* codepoints and swapped in without touching a screen.
#
#   tools/make-icon-font.sh          # generates src/ui/icons_material.[ch]
#   ... then: icon-theme = material  (in your settings file)
#
# Requires Node (for lv_font_conv, MIT) and network access on first run; the
# font is cached under out/ so later runs are offline.
set -e

ROOT=$(cd "$(dirname "$0")/.." && pwd)
CACHE="$ROOT/out/iconfont"
GEN="$ROOT/src/ui"
SIZES=${SIZES:-"14 20 28"}

BASE="https://raw.githubusercontent.com/google/material-design-icons/master/variablefont"
NAME="MaterialSymbolsOutlined[FILL,GRAD,opsz,wght]"
TTF="$CACHE/material-symbols.ttf"
CPS="$CACHE/material-symbols.codepoints"

# Slot order MUST match enum icons::Id in src/ui/icons.h.
#   <material icon name>:<PUA codepoint>
SLOTS="usb:F001 wifi:F002 cable:F003 settings:F004 arrow_back:F005 dark_mode:F006
       movie:F007 bug_report:F008 palette:F009 restart_alt:F00A"

if ! command -v npx >/dev/null 2>&1; then
    echo "error: npx (Node.js) is required for lv_font_conv" >&2
    exit 1
fi

mkdir -p "$CACHE"
if [ ! -f "$TTF" ]; then
    echo "fetching Material Symbols (Apache-2.0)..."
    # --globoff: the filename contains [ ] which curl would treat as a range.
    curl -fsSL --globoff "$BASE/$NAME.ttf" -o "$TTF"
fi
if [ ! -f "$CPS" ]; then
    curl -fsSL --globoff "$BASE/$NAME.codepoints" -o "$CPS"
fi

# Resolve names -> codepoints from the file Google ships with the font, rather
# than hardcoding hex that silently rots when the set is updated.
ranges=""
for slot in $SLOTS; do
    name=${slot%:*}
    dst=${slot#*:}
    src=$(awk -v n="$name" '$1 == n { print $2; exit }' "$CPS")
    if [ -z "$src" ]; then
        echo "error: '$name' not found in $CPS" >&2
        exit 1
    fi
    printf '  %-12s U+%s -> U+%s\n' "$name" "$src" "$dst"
    ranges="$ranges --range 0x$src=>0x$dst"
done

for size in $SIZES; do
    out="$GEN/icons_material_$size.c"
    echo "generating $(basename "$out")"
    # bpp 4: 16 alpha levels is plenty for monochrome glyphs and a quarter the
    # size of 8bpp. --no-compress keeps decode off the ARM926's critical path.
    npx --yes lv_font_conv@latest \
        --font "$TTF" \
        --size "$size" \
        --bpp 4 \
        --no-compress \
        --format lvgl \
        --lv-font-name "icons_material_$size" \
        $ranges \
        --output "$out" >/dev/null
done

cat > "$GEN/icons_material.h" <<EOF
#ifndef SRC_UI_ICONS_MATERIAL
#define SRC_UI_ICONS_MATERIAL

// GENERATED by tools/make-icon-font.sh -- do not edit.
// Material Symbols (Apache-2.0), subset to the slots in icons.h.

#include <lvgl/lvgl.h>

#ifdef __cplusplus
extern "C"
{
#endif
$(for size in $SIZES; do echo "    extern const lv_font_t icons_material_$size;"; done)
#ifdef __cplusplus
}
#endif

// Icon tier, mirroring the body-font tiers in screen_picker.cpp.
static inline const lv_font_t *icons_material_font(int height)
{
    if (height <= 272)
        return &icons_material_14;
    if (height <= 480)
        return &icons_material_20;
    return &icons_material_28;
}

#endif /* SRC_UI_ICONS_MATERIAL */
EOF

echo
echo "done: $GEN/icons_material.h + icons_material_{$(echo $SIZES | tr ' ' ',')}.c"
echo "rebuild (make clean && make USE_LVGL=1 release), then set: icon-theme = material"
