/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_AAP_PROTOBUF_SERVICE_SERVICE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_AAP_PROTOBUF_SERVICE_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/sensorsource/SensorSourceService.pb.h"
#include "aap_protobuf/service/media/sink/MediaSinkService.pb.h"
#include "aap_protobuf/service/inputsource/InputSourceService.pb.h"
#include "aap_protobuf/service/media/source/MediaSourceService.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_Service {
    int32_t id;
    bool has_sensor_source_service;
    aap_protobuf_service_sensorsource_SensorSourceService sensor_source_service;
    bool has_media_sink_service;
    aap_protobuf_service_media_sink_MediaSinkService media_sink_service;
    bool has_input_source_service;
    aap_protobuf_service_inputsource_InputSourceService input_source_service;
    bool has_media_source_service;
    aap_protobuf_service_media_source_MediaSourceService media_source_service;
} aap_protobuf_service_Service;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_Service_init_default {0, false, aap_protobuf_service_sensorsource_SensorSourceService_init_default, false, aap_protobuf_service_media_sink_MediaSinkService_init_default, false, aap_protobuf_service_inputsource_InputSourceService_init_default, false, aap_protobuf_service_media_source_MediaSourceService_init_default}
#define aap_protobuf_service_Service_init_zero   {0, false, aap_protobuf_service_sensorsource_SensorSourceService_init_zero, false, aap_protobuf_service_media_sink_MediaSinkService_init_zero, false, aap_protobuf_service_inputsource_InputSourceService_init_zero, false, aap_protobuf_service_media_source_MediaSourceService_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_Service_id_tag      1
#define aap_protobuf_service_Service_sensor_source_service_tag 2
#define aap_protobuf_service_Service_media_sink_service_tag 3
#define aap_protobuf_service_Service_input_source_service_tag 4
#define aap_protobuf_service_Service_media_source_service_tag 5

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_Service_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sensor_source_service,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media_sink_service,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  input_source_service,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media_source_service,   5)
#define aap_protobuf_service_Service_CALLBACK NULL
#define aap_protobuf_service_Service_DEFAULT NULL
#define aap_protobuf_service_Service_sensor_source_service_MSGTYPE aap_protobuf_service_sensorsource_SensorSourceService
#define aap_protobuf_service_Service_media_sink_service_MSGTYPE aap_protobuf_service_media_sink_MediaSinkService
#define aap_protobuf_service_Service_input_source_service_MSGTYPE aap_protobuf_service_inputsource_InputSourceService
#define aap_protobuf_service_Service_media_source_service_MSGTYPE aap_protobuf_service_media_source_MediaSourceService

extern const pb_msgdesc_t aap_protobuf_service_Service_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_Service_fields &aap_protobuf_service_Service_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_AAP_PROTOBUF_SERVICE_SERVICE_PB_H_MAX_SIZE aap_protobuf_service_Service_size
#define aap_protobuf_service_Service_size        2475

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
